[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c \"print('Build complete')\""]

[start]
cmd = "python gfx_trading_bot.py"